services:
  blog-backend:
    image: 'whichisyou/blog-iso'
    container_name: 'blog-backend'
    depends_on:
      - database-service
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://database-service:5432/blog_db
      - SPRING.DATASOURCE.USERNAME=demo
      - SPRING.DATASOURCE.PASSWORD=secret
      - SPRING.JPA.HIBERNATE.DDL-AUTO=none
      - SPRING.JPA.SHOW-SQL=true
    ports:
      - 8888:8080
  database-service:
    image: 'postgres'
    container_name: 'database-service'
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blog_db
    ports:
      - 2345:5432
  test-database-service:
    image: 'postgres'
    container_name: 'test-database-service'
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blog_db
    ports:
      - 2346:5432